### ISSUE TITLE
Gibts dafia a .exe?

### ISSUE THREAD

**Issue by EinboeckFranz** [SchoolRepos/AUD-jpg2word#1]
He des is koa *.exe, wos soidn des?

**Comment by oagna** [comment]
Sehr geehrter Herr Einböck,

bei genauerem betrachten von unserem Repository ist Ihnen sicherlich der Punkt "Releases" auf der rechten Seite nicht aufgefallen. Wenn man wüsste wie Github funktioniert wäre man natürlich bei den Releases schnell fündig geworden.
Hier der besagte Release mit der .exe welche Sie vermutlich suchen: [Release Topsl-Fix-Fehla](https://github.com/SchoolRepos/AUD-jpg2word/releases/tag/topsl-fix-fehla)

Mit freundlichen Grüßen
Andreas

**Comment by littlegamer757** [comment]
butz bruda

**Comment by EinboeckFranz** [comment]
Donn hau's doch wenigstens in da README.md eine. Ah woat des host eh gsogt dasd mochst. Hod guad passt.
